# Generated by Django 4.1.3 on 2022-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbraille', '0002_remove_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='date',
        ),
        migrations.AddField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
